<?php
// $Id$


/**
 * @file
 *   This module provides a CCK Field, that can control field access on other
 *   fields of the same node for different audience groups.
 */


/**
 * Implementation of hook_field_access().
 *
 * This implementation controls the whole module functionality. The rest of the
 * functions is "only" for loading and saving settings and configuration. Ok
 * there is the field itself and the widget, too.
 */
function faf_field_access($op, $field, $account, $node = NULL) {

  switch ($op) {
    case 'view':
    //case 'edit':
      $field_string = $node->type .':'. $field['field_name'];
      $restricted_fields = _faf_get_restricted_fields();

      if (key_exists($field_string, $restricted_fields)) {
        $access = array();
        // If all existent faf_fields restrict access
        foreach ($restricted_fields[$field_string] as $faf_field => $dominant_denial) {
          if (isset($node->$faf_field) && count($node->$faf_field)) {
            $grant = FALSE;
            foreach($node->$faf_field as $item) {
              $preset = $item['value'];
              // Empty value means no restriction
              if ($preset == '') {
                $grant = TRUE;
                break;
              }
              // Check restriction on audience preset.
              $grant = audience_is_member_of($preset, $account, array('node' => $node));
              if ($grant) break;
            }
            // Dominant denial will restrict access directly.
            if ($dominant_denial && !$grant) {
              return FALSE;
            }
            $access[] = $grant;
          }
        }
        // If any faf field was present, and no one granted access, deny it.
        if (count($access) && !count(array_filter($access))) {
          return FALSE;
        }
      }
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function faf_theme() {
  return array(
    'faf_select' => array(
      'arguments' => array('element' => NULL),
    ),
    'faf_buttons' => array(
      'arguments' => array('element' => NULL),
    ),
    'faf_audience_presets_selection' => array(
      'file' => 'faf.admin.inc',
      'arguments' => array('form' => NULL),
    ),

    //'faf_formatter_default' => array(
    //  'arguments' => array('element'),
    //),
    //'faf_formatter_plain' => array(
    //  'arguments' => array('element'),
    //),
  );
}


//============ FIELD ==============//

/**
* Implementation of hook_field_info().
*/
function faf_field_info() {
  return array(
    'faf' => array(
      'label' => t('Field Access field'),
      'description' => t('Store node dependent acces control.'),
    ),
  );
}

/**
* Implementation of hook_field_settings().
*/
function faf_field_settings($op, $field) {
  switch ($op) {
    // Create the form element to be used on the field
    // settings form. Field settings will be the same for
    // all shared instances of the same field and should
    // define the way the value will be stored
    // in the database.
    case 'form':
      $form = array();
      // Build audience preset selection form
      $form['audience_presets'] = _faf_audience_presets_selection_form_helper($field);
      $form['fields'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Fields'),
        '#description' => t('Select the fields which access shall be controlled by this field.'),
        '#options' => _faf_get_content_fields(),
        '#default_value' => isset($field['fields'] ) ? $field['fields'] : array(),
      );
      $form['dominant_denial'] = array(
        '#type' => 'checkbox',
        '#title' => t('Dominant denial'),
        '#description' => t('If checked, all fields that are denied by this field are strictly denied and cannot be granted by other faf fields.'),
        '#default_value' => (bool) $fields['dominant_denial'],
      );
      return $form;

    // Return an array of the names of the field settings
    // defined by this module. These are the items that
    // CCK will store in the field definition
    // and they will be available in the $field array.
    // This should match the items defined in 'form' above.
    case 'save':
      return array('audience_presets', 'fields', 'dominant_denial');

    // Define the database storage for this field using
    // the same construct used by schema API. Most fields
    // have only one column, but there can be any number
    // of different columns. After the schema API values,
    // add two optional values to each column,
    //  'views', to define a Views field
    //  'sortable', to add a Views sort field
    case 'database columns':
      $columns['value'] = array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => FALSE,
        'sortable' => TRUE,
        'views' => TRUE,
      );
      return $columns;

    // Optional: Make changes to the default $data array
    // created for Views. Omit this if no changes are
    // needed, use it to add a custom handler or make
    // other changes.
    //case 'views data':
    //  // Start with the $data created by CCK
    //  // and alter it as needed. The following
    //  // code illustrates how you would retrieve
    //  // the necessary data.
    //  $data = content_views_field_views_data($field);
    //  $db_info = content_database_info($field);
    //  $table_alias = content_views_tablename($field);
    //  $field_data = $data[$table_alias][$field['field_name'] .'_value'];
    //  // Make changes to $data as needed here.
    //  return $data;
  }
}

/**
* Custom validation of settings values.
*
* Create callbacks like this to do settings validation.
*/
function _faf_settings_validate($element, &$form_state) {
  //$value = $form_state['values']['max_length'];
  //if ($value && !is_numeric($value)|| $value < 1 || $value > 255) {
  //  form_set_error('max_length', t('"Max length" must be a number between 1 and 255.'));
  //}
}

/**
* Implementation of hook_field().
*/
function faf_field($op, &$node, $field, &$items, $teaser, $page) {
  switch ($op) {
    // Do validation on the field values here. The widget
    // will do its own validation and you cannot make any
    // assumptions about what kind of widget has been used,
    // so don't validate widget values, only field values.
    case 'validate':
      if (is_array($items)) {
        $first = TRUE;
        foreach ($items as $delta => $item) {
          if (($first && $field['required']) || !faf_content_is_empty($item, $field)) {
            // The error_element is needed so that CCK can
            // set an error on the right sub-element when
            // fields are deeply nested in the form.
            $error_element = isset($item['_error_element']) ? $item['_error_element'] : '';
            if (is_array($item) && isset($item['_error_element'])) unset($item['_error_element']);
            $allowed_values = array_keys(faf_allowed_values($field));
            if (!in_array($item['value'], $allowed_values)) {
              form_set_error($error_element, t('%name: the passed value %value is not allowed.', array('%name' => $field['widget']['label'], '%value' => $item['value'])));
            }
            $first = FALSE;
          }
          else {
            // remove empty ones from value
            unset($items[$delta]);
          }
        }
      }
      return $items;

    // This is where you make sure that user-provided
    // data is sanitized before being displayed.
    case 'sanitize':
      foreach ($items as $delta => $item) {
        $faf = check_plain($item['value']);
        $items[$delta]['safe'] = $faf;
      }
  }
}

/**
* Implementation of hook_content_is_empty().
*
* CCK has no way to know if something like a zero is
* an empty value or a valid value, so return
* TRUE or FALSE to a populated field $item array.
* CCK uses this to remove empty multi-value elements
* from forms.
*/
function faf_content_is_empty($item, $field) {
  if (empty($item['value'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Helper function to retrieve allowed values for the field options.
 *
 * This implementation let us use optionwidgets.module cck widgets.
 * @see content_allowed_values().
 *
 * @param $field
 *   field array of cck field
 * @param $with_empty
 *   indicator if empty value shall be passed. Necessary for validation, as on
 *   non-required fields, value might be empty.
 */
function faf_allowed_values($field) {
  $return = array();


  if (!$field['required'] && !$field['multiple']) {
    $return[''] = t('&lt;No access restriction&gt;');
  }
  $presets = audience_presets_as_optionsarray();

  // Narrow down the options, to activated ones, selected in field settings.
  $selected_presets = (array) $field['audience_presets'];
  uasort($selected_presets, '_faf_options_sort');
  foreach ($selected_presets as $key => $val) {
    if (is_array($val) && $val['active'] && isset($presets[$key])) {
      $return[$key] = $presets[$key];
    }
  }
  return $return;
}

/**
 * Function used by uasort to sort structured arrays by weight value.
 */
function _faf_options_sort($a, $b) {
  $a_weight = (is_array($a) && isset($a['weight'])) ? $a['weight'] : 0;
  $b_weight = (is_array($b) && isset($b['weight'])) ? $b['weight'] : 0;
  if ($a_weight == $b_weight) {
    return 0;
  }
  return ($a_weight < $b_weight) ? -1 : 1;
}

/**
 * Function used by array_walk to flatten structured arrays to key by active.
 */
function _faf_options_walk(&$item, $key) {
  if (is_array($item)) {
    if ($item['active']) {
      $item = $key;
    }
    else {
      $item = FALSE;
    }
  }
}

/**
 * Helper form function to build the audience presets selection element.
 */
function _faf_audience_presets_selection_form_helper($field) {
  $form = array(
    '#type' => 'markup',
    '#theme' => 'faf_audience_presets_selection',
    '#title' => t('Audience Presets'),
    '#tree' => TRUE,
    '#description' => t('Select audience types that shall be selectable for the user.<br/> Audience presets can be created or edited on <em>!link</em>', array('!link' => l(t('Audience Preset Settings'), 'admin/build/audience/presets'))),
  );
  $values = $field['audience_presets'];
  $options = audience_presets_as_optionsarray();
  $count = count($options);
  foreach ($options as $name => $label) {
    // Set default options for new presets
    if (!isset($values[$name]) || !is_array($values[$name])) {
      $values[$name] = array(
        'active' => FALSE,
        'weight' => $count,
      );
    }

    $form[$name]['active'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable %audience_preset', array('%audience_preset' => $label)),
      '#default_value' => (bool) $values[$name]['active'],
    );
    $form[$name]['weight'] = array(
      '#type' => 'weight',
      '#title' => t('Weight'),
      '#default_value' => (bool) $values[$name]['weight'],
      '#delta' => $count,
    );
  }
  return $form;
}

/**
 * Helper function to retreive available fields.
 */
function _faf_get_content_fields() {
  $types = content_types();
  $field_types = _content_field_types();

  $options = array();
  foreach ($types as $type_name => $type) {
    if (isset($type['fields']) && count($type['fields'])) {
      foreach ($type['fields'] as $field_name => $field) {
        $key = "$type_name:$field_name";
        $field_type = $field_types[$field['type']];
        $text = t('@node_type - @field_type: @field (@label)', array('@node_type' => $type['name'], '@field_type' => t($field_type['label']), '@label' => t($field['widget']['label']), '@field' => $field['field_name']));
        $options[$key] = (drupal_strlen($text) > 80) ? truncate_utf8($text, 77) . '...' : $text;
      }
    }
  }
  // Sort the list by type, then by field name, then by label.
  //asort($options);

  return $options;
}

/**
 * Helper function that returns an array of the current faf restricted fields
 * with the relevant faf-fields.
 */
function _faf_get_restricted_fields() {
  $restricted_fields = &ctools_static(__FUNCTION__);

  if (!$restricted_fields) {
    $fields = content_fields();
    $restricted_fields = array();
    foreach ($fields as $field_name => $field) {
      if ($field['type'] == 'faf') {
        $restricted = array_filter($field['fields']);
        $dominant_denial = (bool) $field['dominant_denial'];
        foreach ($restricted as $res_name => $res_field) {
          $restricted_fields[$res_name][$field_name] = $dominant_denial;
        }
      }
    }
  }
  return $restricted_fields;
}

/**
 * Implementation of hook_widget_info().
 *
 * We need custom handling of multiple values for the userreference_select
 * widget because we need to combine them into a options list rather
 * than display multiple elements.
 *
 * We will use the content module's default handling for default value.
 *
 * Callbacks can be omitted if default handing is used.
 * They're included here just so this module can be used
 * as an example for custom modules that might do things
 * differently.
 */
function faf_widget_info() {
  return array(
    'faf_select' => array(
      'label' => t('Select list'),
      'field types' => array('faf'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
    'faf_buttons' => array(
      'label' => t('Check boxes/radio buttons'),
      'field types' => array('faf'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}

/**
 * Implementation of FAPI hook_elements().
 */
function faf_elements() {
  return array(
    'faf_select' => array(
      '#input' => TRUE,
      '#columns' => array('value'), '#delta' => 0,
      '#process' => array('faf_select_process'),
    ),
    'faf_buttons' => array(
      '#input' => TRUE,
      '#columns' => array('value'), '#delta' => 0,
      '#process' => array('faf_buttons_process'),
    ),
  );
}

/**
 * Implementation of hook_widget_settings().
 */
function faf_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      $form = array();
      return $form;

    case 'save':
      return array();
  }
}

/**
 * Implementation of hook_widget().
 */
function faf_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  switch ($field['widget']['type']) {
    case 'faf_select':
      $element = array(
        '#type' => 'faf_select',
        '#default_value' => $items,
      );
      break;

    case 'faf_buttons':
      $element = array(
        '#type' => 'faf_buttons',
        '#default_value' => $items,
      );
      break;

  }
  return $element;
}

/**
 * Process an individual element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 *
 * @see faf_buttons_process()
 */
function faf_select_process($element, $edit, $form_state, $form) {
  // The faf_select widget doesn't need to create its own
  // element, it can wrap around the optionwidgets_select element.
  // Add a validation step where the value can be unwrapped.
  $field_key  = $element['#columns'][0];
  $element[$field_key] = array(
    '#type' => 'optionwidgets_select',
    '#default_value' => isset($element['#value']) ? $element['#value'] : '',
    // The following values were set by the content module and need
    // to be passed down to the nested element.
    '#title' => $element['#title'],
    '#required' => $element['#required'],
    '#description' => $element['#description'],
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );
  if (empty($element[$field_key]['#element_validate'])) {
    $element[$field_key]['#element_validate'] = array();
  }
  array_unshift($element[$field_key]['#element_validate'], 'faf_optionwidgets_validate');
  return $element;
}

/**
 * Process an individual element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 *
 * @see userreference_buttons_process()
 */
function faf_buttons_process($element, $edit, $form_state, $form) {
  // The faf_select widget doesn't need to create its own
  // element, it can wrap around the optionwidgets_select element.
  // Add a validation step where the value can be unwrapped.
  $field_key  = $element['#columns'][0];
  $element[$field_key] = array(
    '#type' => 'optionwidgets_buttons',
    '#default_value' => isset($element['#value']) ? $element['#value'] : '',
    // The following values were set by the content module and need
    // to be passed down to the nested element.
    '#title' => $element['#title'],
    '#required' => $element['#required'],
    '#description' => $element['#description'],
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );
  if (empty($element[$field_key]['#element_validate'])) {
    $element[$field_key]['#element_validate'] = array();
  }
  array_unshift($element[$field_key]['#element_validate'], 'faf_optionwidgets_validate');
  return $element;
}

/**
 * Validate a select/buttons element.
 *
 * @see userreference__ptionwidgets_validate
 *
 * Remove the wrapper layer and set the right element's value.
 * We don't know exactly where this element is, so we drill down
 * through the element until we get to our key.
 *
 * We use $form_state['values'] instead of $element['#value']
 * to be sure we have the most accurate value when other modules
 * like optionwidgets are using #element_validate to alter the value.
 */
function faf_optionwidgets_validate($element, &$form_state) {
  $field_key  = $element['#columns'][0];

  $value = $form_state['values'];
  $new_parents = array();
  foreach ($element['#parents'] as $parent) {
    $value = $value[$parent];
    // Use === to be sure we get right results if parent is a zero (delta) value.
    if ($parent === $field_key) {
      $element['#parents'] = $new_parents;
      form_set_value($element, $value, $form_state);
      break;
    }
    $new_parents[] = $parent;
  }
}


/**
 * FAPI theme for an individual elements.
 *
 * The textfield or select is already rendered by the
 * textfield or select themes and the html output
 * lives in $element['#children']. Override this theme to
 * make custom changes to the output.
 *
 * $element['#field_name'] contains the field name
 * $element['#delta]  is the position of this element in the group
 */
function theme_faf_select($element) {
  return $element['#children'];
}

function theme_faf_buttons($element) {
  return $element['#children'];
}